apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth-user
  namespace: traefik
data:
  users: |1
    YWRtaW46eVY2VDBYYXVwRG5wMWEuY2dXQkFPYXhYbWxLNG0vbHNXTXBCemVYYWhYelA2dzJhNG4zSwo=

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth-user