apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth-user
  namespace: traefik
data:
  users: |1
    YWRtaW46JDJ5JDEwJHZRQ2dzV3VPam9XMWtIRHFtcHlGTHVHNGtxTW41YlY3RVJJ
    L3R4bW1oRWdBUU5BN1Q1eGNPCgo=
    
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth-user