apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth-user
  namespace: traefik
data:
  users: |1
    YWRtaW46NTc3NzJ5NTc3NzEwNTc3N3pHckNBaE5KL2RYTzlmUGd2Tm1sSi5qVG1MZ2FmYjRqeWVzVk83d2tjRlp0WER0Z3pDUzFlCg==


---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth-user