apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth-user
  namespace: traefik
stringData:
  users: admin:$2y$10$los7PBpt8ry1pWft6UBof.jPS5WihNhU9QzKh0nabF61XZg1vNuJm

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth-user