apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth-user
  namespace: traefik
data:
  users: |1
    YWRtaW46JCQyeSQkMTAkJGJxaTV2dENlNFVLZnJ4ZFk0S0kxdmV3Qks4S0RsaE81
    Ty4ySWZ3allGSmtHOVQ0SnJoWHZhCgo=


---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: admin-basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    secret: admin-basic-auth-user